### ISSUE TITLE
Vector are not received properly when using thrift

### ISSUE THREAD

**Issue by giuliavezzani** [robotology-playground/localize-superquadrics#1]
We would like to have this thrift service:
```
Vector localize_superq(1: string &object_names, 2: Bottle &points, 3: i32 object_num);
```
returning a Yarp Vector,  defined in the [`idl.thrift`](https://github.com/robotology-playground/localize-superquadrics/blob/master/src/idl.thrift) as:
```
struct Vector
 {
 } (
    yarp.name = "yarp::sig::Vector"
    yarp.includefile="yarp/sig/Vector.h"
 )
```

However, the received value is not correct. In particular, the first two values of the received Bottle are not filled with the correct values.

### Example
The Vector is correctly filled when sent. If we print the Vector just before the return statement, we can check that it is correctly filled.

The Bottle received is instead the following:
```
(6,2362767e-310, 6,2362767e-310, correct_value_2, correct_value_3, ...)
```
missing `correct_value_0` and `correct_value_1`, independently from the dimension of the Vector.

Together with @drdanz,  we investigated a little the problem. but we haven't found a solution yet.

To temporarly fix the bug, the thrift service returns a `std::vector<double>`.

**Comment by drdanz** [comment]
This is a minimum example to reproduce the issue:
https://gist.github.com/drdanz/4634279a3c03e2def9b090061212ba00

Until now I discovered that:
1) The data is corrupted by the writer (using wireshark the data is already corrupted).
2) The first 2 elements are corrupted for `double` (64bit each), the first 4 elements are corrupted for `int` (32bit each) => 16 bytes of memory are somehow corrupted somewhere
3) The data stored in the vector is correct before and after the transmission

**Comment by drdanz** [comment]
This is an even smaller example that does not use thrift:

https://gist.github.com/drdanz/19b2eb8709b4a5fcd8eb09763ee866df

The issue is actually a problem in YARP, I'll open an issue in YARP repository

**Comment by drdanz** [comment]
@giuliavezzani This issue should be fixed by robotology/yarp#2023, I think this issue can be closed

**Comment by giuliavezzani** [comment]
Thanks @drdanz! I'll test the fix and close the issue asap!

**Comment by giuliavezzani** [comment]
@drdanz I finally tested sending and receiving Yarp Vectors via thrift with your fix! It works, thank you! I think we can close this :)
